(()=>{const $=id=>document.getElementById(id);let session=null,poll=null,bank=null;
async function openDashboard(code){session=await DB.findSession(code);if(!session)throw Error("No encontramos una sesion con ese codigo.");try{bank=await fetch("quizzes/"+session.quiz_id+".json?v=4").then(r=>r.json())}catch{bank=null}$("teacherLogin").classList.add("hidden");$("dashboard").classList.remove("hidden");$("sessionTitle").textContent=session.title;$("sessionMeta").textContent="Codigo "+session.code+" · "+session.quiz_id.toUpperCase()+" · maximo "+session.max_teams+" equipos";await refresh();clearInterval(poll);poll=setInterval(refresh,5000)}
async function refresh(){try{const [teams,games]=await Promise.all([DB.getTeams(session.id),DB.getGames(session.id)]);const answers=await DB.getAnswers(games.map(g=>g.id));render(teams,games,answers)}catch(e){console.error(e)}}
function render(teams,games,answers){$("teamsCount").textContent=teams.length+"/"+session.max_teams;const finished=games.filter(g=>g.status==="finished");$("finishedCount").textContent=finished.length;const tc=games.reduce((s,g)=>s+(g.correct_answers||0),0),tq=games.reduce((s,g)=>s+(g.total_questions||0),0);$("avgAccuracy").textContent=tq?Math.round(tc/tq*100)+"%":"-";$("answersCount").textContent=answers.length;$("updatedAt").textContent="Actualizado "+new Date().toLocaleTimeString("es-EC");
const tm=Object.fromEntries(teams.map(t=>[t.id,t])),best={};games.forEach(g=>{if(!best[g.team_id]||g.score>best[g.team_id].score)best[g.team_id]=g});const rows=Object.values(best).sort((a,b)=>b.score-a.score||(a.total_time||999999)-(b.total_time||999999));$("rankingBody").innerHTML=rows.length?rows.map((g,i)=>"<tr><td class='rank'>"+(i<3?["1.","2.","3."][i]:i+1)+"</td><td><b>"+(tm[g.team_id]?.name||"Equipo")+"</b></td><td><b>"+g.score+"</b></td><td>"+g.correct_answers+"/"+g.total_questions+"</td><td>"+(g.total_time?Number(g.total_time).toFixed(1)+" s":"-")+"</td><td><span class='status "+g.status+"'>"+(g.status==="finished"?"Finalizado":"Jugando")+"</span></td></tr>").join(""):"<tr><td colspan='6' class='empty'>Aun no hay equipos jugando.</td></tr>";
const cats={};answers.forEach(a=>{cats[a.category]??={ok:0,n:0};cats[a.category].n++;if(a.is_correct)cats[a.category].ok++});$("categoryAnalytics").innerHTML=Object.entries(cats).sort((a,b)=>a[1].ok/a[1].n-b[1].ok/b[1].n).map(([k,v])=>{const p=Math.round(v.ok/v.n*100);return "<div class='analytic'><div><b>"+k+"</b><span>"+p+"%</span></div><div class='mini-track'><i style='width:"+p+"%'></i></div><small>"+v.ok+" de "+v.n+" correctas</small></div>"}).join("")||"<p class='note'>Esperando respuestas...</p>";
const qs={};answers.forEach(a=>{qs[a.question_id]??={wrong:0,n:0};qs[a.question_id].n++;if(!a.is_correct)qs[a.question_id].wrong++});const qm=bank?Object.fromEntries(bank.questions.map(q=>[q.id,q.question])):{};$("hardQuestions").innerHTML=Object.entries(qs).filter(([,v])=>v.wrong).sort((a,b)=>b[1].wrong-a[1].wrong).slice(0,5).map(([id,v],i)=>"<div class='hard'><b>"+(i+1)+". "+(qm[id]||id)+"</b><span>"+v.wrong+" errores / "+v.n+"</span></div>").join("")||"<p class='note'>Todavia no hay errores registrados.</p>"}
function makeCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let s="";for(let i=0;i<6;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s}
async function createNewSession(){for(let attempt=0;attempt<5;attempt++){const code=makeCode();if(await DB.findSession(code))continue;return await DB.createSession({code,quiz_id:$("newQuiz").value,title:$("newTitle").value.trim()||"Classroom Challenge",status:"active",max_teams:Number($("newMaxTeams").value)||12})}throw Error("No se pudo generar un codigo unico. Intenta nuevamente.")}
$("createSessionForm").onsubmit=async e=>{e.preventDefault();const btn=e.submitter;try{btn.disabled=true;btn.textContent="CREANDO...";const s=await createNewSession();alert("Sesion creada. Codigo para estudiantes: "+s.code);await openDashboard(s.code)}catch(err){alert("No se pudo crear la sesion. "+err.message)}finally{btn.disabled=false;btn.textContent="CREAR SESION"}};
$("teacherForm").onsubmit=async e=>{e.preventDefault();try{await openDashboard($("teacherCode").value.trim().toUpperCase())}catch(err){alert(err.message)}};$("changeSession").onclick=()=>location.reload();const q=new URLSearchParams(location.search).get("session");if(q){$("teacherCode").value=q;openDashboard(q).catch(e=>alert(e.message))}})();